/*****************************************************************************

						ATENTION
						
   DO NOT EDIT THIS FILE. 
   THIS FILE IS AUTOMATIC GENERATED BY MARIAMOLE
   ALL CHANGES IN THIS FILE WILL BE LOST
   
   This file is used by MariaMole to work in a similar way to the original 
   Arduino IDE:
       - Automatically detect undeclared functions (Their prototypes will
	    be put here)
	   - Importing Arduino libraries (Detected .h files will be #include'd
	     here)
	   - etc

    You can disable generating this file at Preferences -> Advanced, but
	then you'll have to write your own code to import Arduino libraries
	header files and you'll have to always declare you functions 
	prototypes (which is a good practices, IMHO :) )	

*****************************************************************************/

//---------------------------------------------------------------------------
#ifndef _MARIAMOLE_AUTOMATIC_CODE_H
#define _MARIAMOLE_AUTOMATIC_CODE_H
//---------------------------------------------------------------------------

#include <Arduino.h>

/*--MARIMOLE-DEF_BEGIN--*/
void loop();
void setup();
/*--MARIMOLE-DEF_END--*/

#endif